# Generated by Django 5.0 on 2024-02-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byuiGrocerConnect', '0002_store_customer_order_orderitem_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
