# Generated by Django 5.0 on 2024-02-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byuiGrocerConnect', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product_images'),
        ),
    ]
